colour = input("enter a colour: ")
plr_noun = input("enter a plural noun: ")
celebrity = input("enter a celebrity: ")
print("roses are " + colour)
print(plr_noun + " are blue")
print("I love " + celebrity)
